### ISSUE TITLE
Support truncation when formatting

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/hex-conservative#101]
The following should work

```rust
format!("{:016x}", hash);
```

I.e we should support truncation by way of the precise formatting paramater because hashes are not integral types.

**Comment by apoelstra** [comment]
I'm certain we support this. This was a feature request on day one and one of the first things we implemented.

**Comment by apoelstra** [comment]
Yeah, weirdly we don't have a unit test in `hashes/` but you can add one

```rust

    #[test]
    fn sha256_truncated() {
        #[rustfmt::skip]
        static HASH_BYTES: [u8; 32] = [
            0xef, 0x53, 0x7f, 0x25, 0xc8, 0x95, 0xbf, 0xa7,
            0x82, 0x52, 0x65, 0x29, 0xa9, 0xb6, 0x3d, 0x97,
            0xaa, 0x63, 0x15, 0x64, 0xd5, 0xd7, 0x89, 0xc2,
            0xb7, 0x65, 0x44, 0x8c, 0x86, 0x35, 0xfb, 0x6c,
        ];

        let hash = sha256::Hash::from_slice(&HASH_BYTES).expect("right number of bytes");

        assert_eq!(
            format!("{:.8}", hash),
            "ef537f25",
        );
    }
```

passes.

**Comment by tcharding** [comment]
Oh nice, you are correct. So the bug is actually in the issue (and in `secp`) 

Wrong: `format!("{:016x}", hash);`
Right: `format!("{:.8}", hash);`

It is width vs precision but I was reading the docs wrong and had them backwards. Thanks

**Comment by apoelstra** [comment]
Yeah, this is a terminology issue in `format_args` that has burned me in the past. In my old `hashes::hex` code I used width because that's what makes intuitive sense. But Kix corrected me that actually "width" means "minimum width" and "precision" means "maximum width". Approximately.

**Comment by Kixunil** [comment]
What confuses *me* more is that `.43` looks like decimal number so it never occurs to me that it should work for anything other than floats.
