### ISSUE TITLE
Are `hex_chars_to_byte` and `FromHex` optimized enough?

### ISSUE THREAD

**Issue by RCasatta** [rust-bitcoin/hex-conservative#115]
It seems to me to much time is spent on this functions in my app, I think they are good candidate for performance optimization

![image](https://github.com/user-attachments/assets/40b79ebd-84f2-4247-8087-7359f18ebf36)

**Comment by tcharding** [comment]
Interesting, here is `hex_chars_to_bytes`:

```rust
fn hex_chars_to_byte(hi: u8, lo: u8) -> Result<u8, InvalidCharError> {
    let hih = (hi as char).to_digit(16).ok_or(InvalidCharError { invalid: hi })?;
    let loh = (lo as char).to_digit(16).ok_or(InvalidCharError { invalid: lo })?;

    let ret = (hih << 4) + loh;
    Ok(ret as u8)
}
```

And here is `to_digit` (from `$RUST_SRC_PATH/core/src/char/methods.rs`:

```rust
    #[inline]
    pub const fn to_digit(self, radix: u32) -> Option<u32> {
        // If not a digit, a number greater than radix will be created.
        let mut digit = (self as u32).wrapping_sub('0' as u32);
        if radix > 10 {
            assert!(radix <= 36, "to_digit: radix is too high (maximum 36)");
            if digit < 10 {
                return Some(digit);
            }
            // Force the 6th bit to be set to ensure ascii is lower case.
            digit = (self as u32 | 0b10_0000).wrapping_sub('a' as u32).saturating_add(10);
        }
        // FIXME: once then_some is const fn, use it here
        if digit < radix { Some(digit) } else { None }
    }
```

I don't see any obvious bottle neck?

**Comment by apoelstra** [comment]
We should check in godbolt and/or add some benchmarks. The existing code looks pretty close to optimal (in particular, after inlining and eliminating branches on the constant `radix`, that giant `to_digit` function will be super small), so to improve it we're going to need to look more closely. An obvious thing to try is to just reimplement `to_digit` in terms of `u8`s. Another good-to-try would be to use a lookup table, but that's not obviously faster than just using `wrapping_sub`s and assumptions about ASCII ordering.

This recent blog post is worth reading https://rundevelopment.github.io/blog/fast-unorm-conversions (though in his case, his original code has `f64` divisions so ofc he was able to get a huge speedup).

**Comment by apoelstra** [comment]
Also lol @ "maybe you haven't optimized enough" when applied to this crate. This crate has been super slow to develop because @Kixunil has put more engineering into it than parts of rust-bitcoin which are 10x as complicated.

Also @RCasatta do you have any comparable benchmarks available using the old `FromHex` impl from `bitcoin_hashes 0.11.0`? I *think* you can add a dependency and then the trait should be a drop-in replacement if you want to do a quick test.

**Comment by apoelstra** [comment]
Actually, the old `FromHex` grounds out in the `chars_to_hex` function which is identical to our `hex_chars_to_byte`: https://github.com/rust-bitcoin/bitcoin_hashes/blob/master/src/hex.rs#L119-L129 except it's buried deeper in a function call chain (but I would expect the optimizer to collapse that all). So my expectation would be that there's not any difference in results.

**Comment by tcharding** [comment]
Hey @RCasatta we are starting to push towards 1.0 on this crate. A few questions please:

1. Are you planning on working on this?
2. If yes do you want it in `v1.0`?
3. Can we not bother answering (1) and (2) because we are confident we can do this without breaking the public API anyways?

**Comment by RCasatta** [comment]
1. Not in the short term
2. No
3. yes, I think any performance improvement should not change the API

#123 already helped a lot (but I've still to see it in prod cause it's not yet in latest bitcoin release)

I whink @tankyleo may have some more ideas to improve `hex_chars_to_byte` taking inspiration from `hex` crate, but at the moment I am happy with the perf and that should have a more specific issue in case.

I think we can close this general one. Thanks

**Comment by tankyleo** [comment]
> I whink @tankyleo may have some more ideas to improve hex_chars_to_byte taking inspiration from hex crate, but at the moment I am happy with the perf and that should have a more specific issue in case.

The idea was to try a rewrite of `hex_chars_to_byte` with something along the lines of `KokaKiwi/rust-hex`:
```
const fn val(c: u8, idx: usize) -> Result<u8, FromHexError> {
    match c {
        b'A'..=b'F' => Ok(c - b'A' + 10),
        b'a'..=b'f' => Ok(c - b'a' + 10),
        b'0'..=b'9' => Ok(c - b'0'),
        _ => Err(FromHexError::InvalidHexCharacter {
            c: c as char,
            index: idx,
        }),
    }
}
```

I've already tried this rewrite, and with my current benchmarking tools, I did not find a clear winner. Happy to revisit if someone requests.

**Comment by tcharding** [comment]
Thanks boys.

**Comment by Kixunil** [comment]
Just to clarify some confusion, I only optimized *encoding*, not decoding. And that's because I saw obvious solutions. In case of decoding I'm pretty sure we could do some SIMD magic (and I guess we should check if encoding is also SIMDified). But that's not a priority for us right now.
