### ISSUE TITLE
Depend on `bitcoin-io`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/hex-conservative#51]
Once we release `bitcoin-io` we want to use it here, right? That would make `bitcoin-io` part of the public API which implies we need to do stable release of `bitcoin-io` before we can do a stable release of this crate.

**Comment by Kixunil** [comment]
I think `bitcoin-io` will never be stable and there's no need to depend on it here. Yeah, `no_std` people don't get readers and writers but everyone else avoids a weird `bitcoin` dependency in a general-purpose crate. Our crates don't need readers and writers and if they do, we can add them to `bitcoin-io` instead.

**Comment by Kixunil** [comment]
> Huh?

I hope `push_decode` will eventually obviate the need for it (before it stabilizes).

> I mean I dont have a need for them, but I assume others do?

Then who are those others? If they speak up, I'd like to work with them to figure out a good solution.

> I mean we can also just rename it to not say "bitcoin" on the tin.

Or rename `bitcoin-io` to `core3` :P
