### ISSUE TITLE
Serde support?

### ISSUE THREAD

**Issue by dpc** [rust-bitcoin/hex-conservative#6]
`#[serde(with="hex::serde")]` is sooo nice to have, and the only reason we are still pulling in `hex` crate into our dependencies. Would it be feasible to support it here (behind an optional feature maybe)?

**Comment by Kixunil** [comment]
I'd definitely like that. Although you can now use `bitcoin::consensus::serde::With` to make consensus-encodable objects encode as hex in human-readable encoders which covers a bunch of cases where this is needed.

**Comment by dpc** [comment]
>  you can now use bitcoin::consensus::serde::With to make consensus-encodable objects encode as hex in human-readable encoders

Good to know, thanks!
