### ISSUE TITLE
Revert committing API changes

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/hex-conservative#78]
IIUC the motivation behind committing API changes was to show the diff of the API. This is really not needed and it's just annoying. We can simply checkout and old commit in CI, generate the API list on it and store in a file, then checkout HEAD and generate the API on that, then just print the diff. For convenience we can have a bot comment with a link to the output if there is a any change.

**Comment by apoelstra** [comment]
FWIW I find the API diff very useful even though it's noisier than I'd like. But I agree it's annoying to regenerate it, esp as you have to do a `cargo install` of a tool with a gazillion no-doubt-unvetted deps.

**Comment by Kixunil** [comment]
> unsure what the practical limits are and whether Github will give us a small box with scrollbars or a huge box that readers have to scroll past.

I'd use `<details>` for that:

<details><summary>API changes</summary>

```
very
long
API
changes
here
```

</details>



> I'm certainly not writing the new tool though.

I could look int o it but it's not a priority for me, so it can take months.

**Comment by apoelstra** [comment]
I'll take it on. I really want these API diffs and finally learned to use GA with my "weekly update compiler pin" PR.

Thanks for the tip on `<details>`!

**Comment by Kixunil** [comment]
> Thanks for the tip on `<details>`!

Just note that if you want to put a code block in there you need to put empty lines around it. Otherwise it'll mess up formatting.

**Comment by tcharding** [comment]
> I'll take it on.

Hey @apoelstra have you still got this on your todo list? I rekon we should get this done by the time we start 1.0'ing crates.

**Comment by tcharding** [comment]
Closing because we removed the API files already.
