### ISSUE TITLE
In v0.1.1, InvalidLength error prints 'expected' and  'got' values swapped

### ISSUE THREAD

**Issue by jirijakes** [rust-bitcoin/hex-conservative#87]
While during parsing the values are in order (want, got):

https://github.com/rust-bitcoin/hex-conservative/blob/bd9c2c7b44bc89e91ec6bb4f7164672e27a43f64/src/parse.rs#L88

`Display` prints them in order (got, want):

https://github.com/rust-bitcoin/hex-conservative/blob/bd9c2c7b44bc89e91ec6bb4f7164672e27a43f64/src/parse.rs#L124-L134

This was, probably inadvertently, later [fixed](https://github.com/rust-bitcoin/hex-conservative/pull/44/files#diff-5583e398a8deec11b274d9965eff8b5ade5226c7a020ca214a27d7d07dcc8a29L89-R62) and v0.2.0 does not suffer from it anymore.

The issue is that rust-bitcoin v0.31.2 depends on hex-conservative v0.1.1 and therefore the error messages in v0.31.2 are incorrect. I know it's too tiny an issue, but if there is will to have this fixed (I can help), perhaps the solution would be to publish v0.1.2 with fix and let rust-bitcoin v0.31.3 depend on it?

---

Background: I am upgrading rust-lightning to rust-bitcoin v0.31 (see [#2745](https://github.com/lightningdevkit/rust-lightning/issues/2745)) and it so happens that rust-lightning has a [test](https://github.com/lightningdevkit/rust-lightning/blob/d3cd0802532d869fdc2b1a620cc76b647895cc54/lightning-block-sync/src/convert.rs#L604-L626) which fails with v0.31 due to this issue. I have not yet opened PR on rust-lightning, may do so tomorrow.

```
failures:

---- convert::tests::into_txid_from_json_response_with_invalid_hex_data stdout ----
thread 'convert::tests::into_txid_from_json_response_with_invalid_hex_data' panicked at lightning-block-sync/src/convert.rs:610:17:
assertion `left == right` failed
  left: "bad hex string length 64 (expected 6)"
 right: "bad hex string length 6 (expected 64)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- convert::tests::into_txid_from_json_response_with_invalid_txid_data stdout ----
thread 'convert::tests::into_txid_from_json_response_with_invalid_txid_data' panicked at lightning-block-sync/src/convert.rs:622:17:
assertion `left == right` failed
  left: "bad hex string length 64 (expected 4)"
 right: "bad hex string length 4 (expected 64)"


failures:
    convert::tests::into_txid_from_json_response_with_invalid_hex_data
    convert::tests::into_txid_from_json_response_with_invalid_txid_data
```

**Comment by apoelstra** [comment]
Yeah, I'd be open to doing a minor release of hex-conservative for this. It looks like the offending code is entirely in hex-conservative though so we wouldn't need to do a release of rust-bitcoin?

**Comment by jirijakes** [comment]
I am afraid it may be needed, because rust-bitcoin's hash types use hex-conservative's `FromHex` and `HexToArrayError` to [implement](https://github.com/rust-bitcoin/rust-bitcoin/blob/89d6991cf1a04d283bdb71ae61320831739e1699/hashes/src/util.rs#L270-L281) `FromStr`.

```rust
use std::str::FromStr;

fn main() {
    println!("{}", bitcoin::hash_types::Txid::from_str("abcd").unwrap_err());
}
```

```
bad hex string length 64 (expected 4)
```

**Comment by apoelstra** [comment]
Yes but if we release a new minor version, users of rust-bitcoin can automatically use it, and will get the updated `HexToArrayError` and `FromHex`.

**Comment by jirijakes** [comment]
Ah, true.

Alright, then I will prepare patch.

Thanks, Andrew.

**Comment by tcharding** [comment]
Thanks, I created a branch `0.1.x` that you can use as target branch for the PR. You'll need to invert the values in the unit test `hex_to_array_error` also.

 FTR I also confirmed that this bug does not exist in `v0.2.0`.

Thanks for the issue, super useful to get bug reports no matter how minor.

**Comment by jirijakes** [comment]
Thanks, @tcharding!

**Comment by Kixunil** [comment]
OMG, this is silly, why we're using unnamed fields if there's more than one?!
