### ISSUE TITLE
Question: implement `FromHex` for `ArrayVec` ?

### ISSUE THREAD

**Issue by irriden** [rust-bitcoin/hex-conservative#95]
Let me know what you think of the snippet below. This panics in case the `ArrayVec` runs out of capacity. To return an error, I would need to return `InvalidChar`, `OddLengthString`, and `InvalidLength` all under one error.

I am in `no-std` with no `alloc`, and I need to parse some hex strings I don't know the length of, but I know for sure will be below a reasonable length.

Thank you!

```
impl<const LEN: usize> FromHex for ArrayVec<u8, LEN> {
    type Error = HexToBytesError;

    fn from_hex(s: &str) -> Result<Self, Self::Error> {
        let mut ret = ArrayVec::<u8, LEN>::new();
        for byte in HexToBytesIter::new(s)? {
            ret.push(byte?);
        }
        Ok(ret)
    }
}
```

**Comment by apoelstra** [comment]
This is tempting. The panic is a little unfortunate. Maybe this should be a dedicated method rather than a `FromHex` impl?

**Comment by Kixunil** [comment]
We can't do that since `arrayvec` is not stable yet and we'd like to stabilize eventually.
